name: Build and demo web app

env:
  NODE_VERSION: "14.x"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-web-app:
    name: "Deploy web app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install latest stable Rust version
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web-app/${{ matrix.example }}

      - name: Build WASM
        run: yarn run build
        working-directory: web-app/${{ matrix.example }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0
        with:
          publish-dir: "./dist"
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}